# frozen_string_literal: true

require 'json'
require 'digest'
require 'fileutils'
require_relative 'triage_event'

# Delivery/mute state and verbatim prior replies, not a model of conversation meaning.
class ConversationState
  attr_reader :data, :loaded

  def initialize(directory, scope)
    @path = File.join(directory, "#{Digest::SHA256.hexdigest(scope)}.json") if directory
    @data = { 'version' => 1, 'seen' => [], 'replies' => [], 'muted' => false }
    return unless @path && File.file?(@path)

    saved = JSON.parse(File.read(@path))
    return unless saved.is_a?(Hash) && saved['version'] == 1 &&
                  %w[seen replies].all? { |key| saved[key].is_a?(Array) && saved[key].all?(String) }

    @data = saved.slice('version', 'seen', 'replies', 'muted', 'processed', 'initial_assessed', 'maintainer_replied')
    @loaded = true
  rescue JSON::ParserError
    nil
  end

  def seen?(comment)
    @data['seen'].include?(signature(comment))
  end

  def signature(comment)
    Digest::SHA256.hexdigest(JSON.generate(comment.values_at('id', 'body', 'authorAssociation')))
  end

  def observe(comments)
    comments.each do |comment|
      next if seen?(comment)

      @data['seen'] = (@data['seen'] + [signature(comment)]).last(100)
      body = comment.fetch('body')
      if TriageEvent.bot?(comment['author'])
        remember_reply(body.split("\n\n_Generated by [Copilot Triage](", 2).first.to_s) if
          body.include?('Generated by [Copilot Triage]')
      elsif TriageEvent.maintainer?(comment['authorAssociation']) && TriageEvent.command(body) == 'unmute'
        @data['muted'] = false
      elsif TriageEvent.command(body) == 'mute'
        @data['muted'] = true
      elsif TriageEvent.maintainer?(comment['authorAssociation']) && !TriageEvent.command(body)
        @data['maintainer_replied'] = true
      end
    end
  end

  def remember_reply(body)
    @data['replies'] = (@data['replies'] + [body]).uniq.last(30) unless body.empty?
  end

  def processed?(fingerprint)
    @data['processed'] == fingerprint
  end

  def complete(fingerprint, body, reply_posted: false)
    @data['processed'] = fingerprint
    remember_reply(body) if reply_posted && body
  end

  def save
    return unless @path

    FileUtils.mkdir_p(File.dirname(@path))
    temporary = "#{@path}.tmp"
    File.write(temporary, JSON.generate(@data))
    File.rename(temporary, @path)
  end

  def prompt_context
    context = []
    @data['replies'].reverse_each do |reply|
      break if JSON.generate([reply, *context]).bytesize > 4000

      context.unshift(reply)
    end
    context
  end
end
