# frozen_string_literal: true

require 'json'
require 'digest'
require 'fileutils'
require_relative 'triage_event'

# Cached across runs; public bot questions and stop requests are recoverable from GitHub.
class ConversationState
  attr_reader :data, :loaded

  def initialize(directory, scope)
    @path = File.join(directory, "#{Digest::SHA256.hexdigest(scope)}.json") if directory
    @data = { 'version' => 1, 'seen' => [], 'questions' => [], 'replies' => [], 'facts' => [], 'muted' => false }
    return unless @path && File.file?(@path)

    saved = JSON.parse(File.read(@path))
    return unless saved.is_a?(Hash) && saved['version'] == 1 &&
                  %w[seen questions replies].all? { |key| saved[key].is_a?(Array) && saved[key].all?(String) }

    @data = saved
    @loaded = true
  rescue JSON::ParserError
    nil
  end

  def seen?(comment)
    @data['seen'].include?(signature(comment))
  end

  def signature(comment)
    Digest::SHA256.hexdigest(JSON.generate(comment.values_at('id', 'body', 'authorAssociation')))
  end

  def observe(comments, latest_id: nil)
    comments.each do |comment|
      next if seen?(comment)

      @data['seen'] = (@data['seen'] + [signature(comment)]).last(100)
      body = comment.fetch('body')
      unless TriageEvent.bot?(comment['author'])
        @data['facts'] = (@data.fetch('facts', []) + TriageEvent.evidence_signals(body)).uniq.last(256)
      end
      if TriageEvent.bot?(comment['author'])
        if body.include?('Generated by [Copilot Triage]')
          remember_reply(body.split("\n\n_Generated by [Copilot Triage](",
                                    2).first.to_s)
        end
      elsif TriageEvent.maintainer?(comment['authorAssociation']) && TriageEvent.command(body) == 'unmute'
        @data['muted'] = false
      elsif TriageEvent.command(body) == 'mute' || TriageEvent.stop_requested?(body)
        @data['muted'] = true
      elsif TriageEvent.maintainer?(comment['authorAssociation']) && !TriageEvent.command(body)
        @data['maintainer_replied'] = true
        @data['pending_question'] = nil
      elsif comment['id'] != latest_id && !TriageEvent.acknowledgement?(body)
        @data['pending_question'] = nil
      end
    end
  end

  def remember_reply(body)
    return if body.empty?

    @data['replies'] = (@data['replies'] + [body]).uniq.last(30)
    unless TriageEvent.prose(body).include?('?')
      @data['pending_question'] = nil
      return
    end

    @data['questions'] = (@data['questions'] + [body]).uniq.last(20)
    @data['pending_question'] = body
  end

  def processed?(fingerprint)
    @data['processed'] == fingerprint
  end

  def complete(fingerprint, body, reply_posted: false, question_answered: false)
    @data['processed'] = fingerprint
    @data.delete('unprocessed_evidence')
    @data['last_answered_question'] = @data.delete('pending_question') if @data['pending_question'] && question_answered
    remember_reply(body) if reply_posted && body
  end

  def save
    return unless @path

    FileUtils.mkdir_p(File.dirname(@path))
    temporary = "#{@path}.tmp"
    File.write(temporary, JSON.generate(@data))
    File.rename(temporary, @path)
  end

  def prompt_context
    context = @data.slice('pending_question', 'last_answered_question', 'maintainer_replied')
    context['questions'] = []
    @data['questions'].reverse_each do |question|
      break if JSON.generate(context.merge('questions' => [question, *context['questions']])).bytesize > 4000

      context['questions'].unshift(question)
    end
    context
  end
end
