# frozen_string_literal: true

require_relative '../lib/assessment'

RSpec.describe 'Comment attribution' do
  let(:environment) do
    { 'GITHUB_REPOSITORY' => 'crmne/example', 'TRIAGE_NUMBER' => '1', 'TRIAGE_CONFIG' => 'triage.yml',
      'TRIAGE_MODEL' => 'gpt-5.6-luna', 'GITHUB_RUN_ID' => '1234', 'GITHUB_RUN_ATTEMPT' => '2' }
  end
  let(:assessment) { IssueAssessment.new(environment) }
  let(:item) do
    { 'id' => 'item', 'title' => 'Question', 'body' => 'A report', 'closed' => false,
      'author' => { 'login' => 'reporter' }, 'comments' => { 'nodes' => [] } }
  end
  let(:response) { JSON.generate(labels: [], reply: 'version', files: []) }

  before do
    allow(assessment).to receive(:puts)
    allow(assessment).to receive_messages(read_report: [item, []], ask_copilot: response)
    allow(assessment).to receive(:mutate)
  end

  def usage(input, output)
    File.write('usage.json', JSON.generate(modelMetrics: { 'gpt-5.6-luna' => {
                                             usage: { inputTokens: input, outputTokens: output, cacheReadTokens: 3000,
                                                      cacheWriteTokens: 1000 },
                                             requests: { count: 1 }
                                           } }))
    assessment.send(:record_usage, 'usage.json')
  end

  def posted_body
    body = nil
    expect(assessment).to receive(:mutate).with('addComment', anything) { |_, input| body = input[:body] }
    assessment.run
    body
  end

  it 'links the marketplace and exact run attempt with measured token usage' do
    allow(assessment).to receive(:ask_copilot) {
      usage(6000, 50)
      response
    }

    body = posted_body

    expect(body).to start_with('Which RubyLLM version are you using?')
    expect(body).to include('[Copilot Triage](https://github.com/marketplace/actions/copilot-triage)',
                            'using `gpt-5.6-luna`', '6000 input / 50 output tokens this run',
                            '[view run](https://github.com/crmne/example/actions/runs/1234/attempts/2)')
  end

  it 'adds usage across both prompts without counting nested or cache totals again' do
    allow(assessment).to receive(:ask_copilot) do
      usage(6000, 50)
      JSON.generate(labels: [], reply: nil, files: ['lib/ruby_llm/tool.rb'])
    end.once
    allow(assessment).to receive(:ask_copilot).with(include('Sources:')) do
      usage(8000, 100)
      JSON.generate(comment: nil, sources: [])
    end

    assessment.run

    expect(assessment.send(:attributed, 'An answer.')).to include('14000 input / 150 output tokens this run')
  end

  it 'reports zero new tokens when an earlier preview is applied from cache' do
    environment.merge!('TRIAGE_CACHE_DIR' => 'cache', 'TRIAGE_DRY_RUN' => 'true')
    assessment.run
    environment['TRIAGE_DRY_RUN'] = 'false'
    cached = IssueAssessment.new(environment)
    allow(cached).to receive_messages(read_report: [item, []], puts: nil, mutate: nil)
    expect(cached).not_to receive(:ask_copilot)
    expect(cached).to receive(:mutate).with('addComment',
                                            hash_including(body: include('cached response; 0 new model tokens')))

    cached.run
  end

  it 'does not claim zero tokens when CLI usage is unavailable' do
    expect(posted_body).to include('token usage unavailable')
  end

  it 'does not lose the answer when optional usage JSON is malformed' do
    allow(assessment).to receive(:ask_copilot) do
      File.write('usage.json', '{invalid')
      assessment.send(:record_usage, 'usage.json')
      response
    end

    expect(posted_body).to include('token usage unavailable')
  end

  it 'does not repeat an earlier answer just because its attribution differs' do
    item['comments']['nodes'] = [
      { 'body' => "Which RubyLLM version are you using?\n\n_Generated by " \
                  '[Copilot Triage](https://example.com) old usage._',
        'author' => { 'login' => 'github-actions[bot]' } },
      { 'body' => 'I do not know.', 'author' => { 'login' => 'reporter' } }
    ]

    assessment.run

    expect(assessment).not_to have_received(:mutate).with('addComment', anything)
  end
end
