# frozen_string_literal: true

require_relative '../lib/assessment'

RSpec.describe 'Conversation memory and selective follow-ups' do
  let(:environment) do
    { 'GITHUB_REPOSITORY' => 'owner/project', 'TRIAGE_NUMBER' => '1', 'TRIAGE_CONFIG' => 'triage.yml',
      'TRIAGE_STATE_DIR' => 'state', 'GITHUB_EVENT_NAME' => 'issue_comment', 'GITHUB_EVENT_PATH' => 'event.json',
      'TRIAGE_DEBOUNCE_SECONDS' => '0' }
  end
  let(:comment) do
    { 'id' => 'human-1', 'body' => 'It still uses 90% CPU after restarting.',
      'author' => { '__typename' => 'User', 'login' => 'reporter' }, 'authorAssociation' => 'NONE' }
  end
  let(:item) do
    { 'id' => 'issue-1', 'title' => 'High idle CPU', 'body' => 'Idle CPU is 90% on version 1.2.3.',
      'closed' => false, 'author' => { 'login' => 'reporter' }, 'comments' => { 'nodes' => [comment] } }
  end
  let(:decision) { JSON.generate(labels: [], reply: nil, sources: []) }

  before do
    config = YAML.safe_load_file('triage.yml')
    config.delete('followups')
    File.write('triage.yml', config.to_yaml)
  end

  def assessment
    event = { 'action' => 'created', 'sender' => { 'type' => 'User' }, 'issue' => { 'state' => 'open' },
              'comment' => { 'node_id' => comment['id'], 'body' => comment['body'],
                             'user' => comment['author'], 'author_association' => comment['authorAssociation'] } }
    IssueAssessment.new(environment).tap do |runner|
      allow(runner).to receive(:event).and_return(event)
      allow(runner).to receive(:read_report).and_return([item, []])
      allow(runner).to receive(:ask_copilot).and_return(decision)
      allow(runner).to receive(:mutate)
      allow(runner).to receive(:puts)
    end
  end

  def bot_question
    { 'id' => 'bot-1', 'body' => "Which RubyLLM version are you using?\n\n_Generated by [Copilot Triage](link)._",
      'author' => { '__typename' => 'Bot', 'login' => 'github-actions' } }
  end

  it 'lets the agent decide whether an ordinary update needs help' do
    runner = assessment
    runner.run
    expect(runner).to have_received(:ask_copilot).once
    expect(runner).not_to have_received(:mutate).with('addComment', anything)
  end

  it 'assesses a new question and skips delivery of the same event again' do
    comment['body'] = 'How can I disable animations?'
    first = assessment
    first.run
    second = assessment
    second.run
    expect(first).to have_received(:ask_copilot).once
    expect(second).not_to have_received(:ask_copilot)
  end

  [
    'I upgraded to 1.3.0 and it behaves differently.',
    'It now uses 98% CPU instead.',
    'Error: image decoder failed with unsupported format.',
    'Steps to reproduce: open an archived chat, then scroll to the oldest image.',
    'It now crashes when I open settings.',
    "Thanks!\n```\nError: image decoder failed.\n```",
    "1. Open a chat\n2. Play a sticker\n3. Minimize the window"
  ].each do |body|
    it "assesses substantive new evidence without requiring a question: #{body}" do
      comment['body'] = body
      runner = assessment
      runner.run
      expect(runner).to have_received(:ask_copilot).once
    end
  end

  it 'remembers verbatim bot replies but leaves subsequent updates to the agent' do
    item['comments']['nodes'].unshift(bot_question)
    comment['body'] = 'Version 1.2.3'
    first = assessment
    first.run
    expect(first).to have_received(:ask_copilot).once
    saved = JSON.parse(File.read(Dir['state/*.json'].first))
    expect(saved['replies']).to include('Which RubyLLM version are you using?')
    expect(saved).not_to have_key('pending_question')

    comment['id'] = 'human-2'
    comment['body'] = 'Still happens after another restart.'
    item['comments']['nodes'] = [comment]
    second = assessment
    second.run
    expect(second).to have_received(:ask_copilot).once
  end

  it 'suppresses a question remembered beyond the latest five comments' do
    state = ConversationState.new('state', 'owner/project/issue/1/report')
    state.remember_reply('Which RubyLLM version are you using?')
    state.save
    comment['body'] = 'Version 1.2.3'
    runner = assessment
    allow(runner).to receive(:ask_copilot).and_return(JSON.generate(labels: [], reply: 'version', sources: []))
    runner.run
    expect(runner).to have_received(:ask_copilot).with(include('Which RubyLLM version are you using?'))
    expect(runner).not_to have_received(:mutate).with('addComment', anything)
  end

  it 'keeps a conversation muted after the stop request falls outside recent comments' do
    comment['body'] = 'Please disable the Copilot bot.'
    first = assessment
    allow(first).to receive(:ask_copilot).and_return(JSON.generate(labels: [], reply: nil, sources: [], mute: true))
    first.run
    comment['id'] = 'human-2'
    comment['body'] = 'What can I try next?'
    runner = assessment
    runner.run
    expect(runner).not_to have_received(:ask_copilot)
    expect(runner).not_to have_received(:mutate)
  end

  it 'allows a maintainer to unmute without posting or spending tokens' do
    comment['body'] = '/triage mute'
    assessment.run
    comment.merge!('id' => 'owner-1', 'body' => '/triage unmute', 'authorAssociation' => 'OWNER')
    runner = assessment
    runner.run
    expect(runner).not_to have_received(:ask_copilot)
    expect(runner).not_to have_received(:mutate)
    expect(JSON.parse(File.read(Dir['state/*.json'].first))['muted']).to be(false)
  end

  it 'does not allow another participant to unmute the conversation' do
    comment['body'] = '/triage mute'
    assessment.run
    comment.merge!('id' => 'human-2', 'body' => '/triage unmute')
    runner = assessment
    runner.run
    expect(runner).not_to have_received(:ask_copilot)
    expect(JSON.parse(File.read(Dir['state/*.json'].first))['muted']).to be(true)
  end

  it 'allows an explicit reassessment by a maintainer' do
    comment.merge!('body' => '/triage', 'authorAssociation' => 'OWNER')
    runner = assessment
    runner.run
    expect(runner).to have_received(:ask_copilot).once
  end

  it 'does not save mute or completion state during previews' do
    environment['TRIAGE_DRY_RUN'] = 'true'
    comment['body'] = '/triage mute'
    assessment.run
    expect(Dir['state/*.json']).to be_empty
  end

  it 'recovers an older stop request when the cache is missing' do
    item['comments']['pageInfo'] = { 'hasPreviousPage' => true, 'startCursor' => 'cursor' }
    old = comment.merge('id' => 'old', 'body' => '/triage mute')
    runner = assessment
    allow(runner).to receive(:github).and_return('data' => { 'node' => {
                                                   'comments' => { 'nodes' => [old],
                                                                   'pageInfo' => { 'hasPreviousPage' => false } }
                                                 } })
    runner.run
    expect(runner).not_to have_received(:ask_copilot)
    expect(JSON.parse(File.read(Dir['state/*.json'].first))['muted']).to be(true)
  end

  it 'recovers comments missed between runs even with existing cached state' do
    state = ConversationState.new('state', 'owner/project/issue/1/report')
    old = comment.merge('id' => 'old', 'body' => 'Earlier update')
    state.observe([old])
    state.save
    item['comments']['pageInfo'] = { 'hasPreviousPage' => true, 'startCursor' => 'cursor' }
    stop = comment.merge('id' => 'missed', 'body' => '/triage mute')
    runner = assessment
    allow(runner).to receive(:github).and_return('data' => { 'node' => {
                                                   'comments' => { 'nodes' => [old, stop],
                                                                   'pageInfo' => { 'hasPreviousPage' => true } }
                                                 } })
    runner.run
    expect(runner).to have_received(:github).once
    expect(runner).not_to have_received(:ask_copilot)
  end

  it 'does not consume an event when inference fails' do
    comment['body'] = 'How can I fix this?'
    first = assessment
    allow(first).to receive(:ask_copilot).and_return(nil)
    first.run
    second = assessment
    second.run
    expect(second).to have_received(:ask_copilot).once
  end

  it 'retries substantive new evidence after inference fails' do
    comment['body'] = 'Error: image decoder failed'
    first = assessment
    allow(first).to receive(:ask_copilot).and_return(nil)
    first.run
    second = assessment
    second.run
    expect(second).to have_received(:ask_copilot).once
  end

  it 'supports assessing all substantive comments when configured' do
    config = YAML.safe_load_file('triage.yml').merge('followups' => 'all')
    File.write('triage.yml', config.to_yaml)
    runner = assessment
    runner.run
    expect(runner).to have_received(:ask_copilot).once
  end

  it 'leaves automatic comments alone when follow-ups are disabled' do
    config = YAML.safe_load_file('triage.yml').merge('followups' => 'off')
    File.write('triage.yml', config.to_yaml)
    comment['body'] = 'How can I fix this?'
    runner = assessment
    runner.run
    expect(runner).not_to have_received(:ask_copilot)
  end

  it 'writes a prepared snapshot without calling the model or requiring its token' do
    comment['body'] = 'How can I fix this?'
    environment.merge!('TRIAGE_PREPARE_ONLY' => 'true', 'TRIAGE_PREPARED_PATH' => 'prepared.json',
                       'GITHUB_OUTPUT' => 'output')
    runner = assessment
    runner.run
    expect(runner).not_to have_received(:ask_copilot)
    expect(File.read('output')).to include('eligible=true')
    expect(JSON.parse(File.read('prepared.json')).fetch('report').first).to eq(item)
  end

  it 'rejects a prepared reply if the report changed before publishing' do
    comment['body'] = 'How can I fix this?'
    environment.merge!('TRIAGE_PREPARE_ONLY' => 'true', 'TRIAGE_PREPARED_PATH' => 'prepared.json',
                       'GITHUB_OUTPUT' => 'output')
    assessment.run
    environment.delete('TRIAGE_PREPARE_ONLY')
    comment['body'] = 'Never mind, solved.'
    runner = assessment
    runner.run
    expect(runner).not_to have_received(:mutate)
  end
end
